# Use postgres 9.6 as base (Heroku postgres default)
FROM postgres:9.6

ENV POSTGRES_USER cageur_user
ENV POSTGRES_PASSWORD 123456
ENV POSTGRES_DB cageur_db

# Postgres binds to port 5432
EXPOSE 5432
